### ISSUE TITLE
[web] Switch to vuepress from nuxt.js

### ISSUE THREAD

**Issue by at15** [xephonhq/awesome-time-series-database#52]
Currently the [website](https://github.com/xephonhq/awesome-time-series-database) is built using https://github.com/nuxt/nuxt.js, however the author of vue released a similar tool https://github.com/vuejs/vuepress 

Reason for making the switch

- I forgot how to use nuxt.js since it's been so long for PR #41 , since I have to learn nuxt.js again if I am going to use it, I'd rather learn vuepress
- angular universal is not usable, and it seems few attention is paid into it
- vuepress has
  - builtin markdown support
  - theme for building documentation site

**Comment by koppor** [comment]
Besides, I would think to switch to plain markdown. This allows for inclusion in the [awesome list](https://github.com/sindresorhus/awesome). See point 3 of the checklist at https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md#requirements-for-your-awesome-list. Since this is the most popular list of awesome lists, it is IMHO a worthy aim.

Besides that, the list could be easily included in the definitive lists of lists at https://github.com/jnv/lists.

**Comment by at15** [comment]
@koppor  I was thinking about using plain markdown like most awesome-lists, but a very long markdown file is hard to filter based on multiple properties. 

It is also possible to only generate website and maintain the README.md file manually. I'll start sorting things out this week and adding sections for papers and benchmarks.

**Comment by koppor** [comment]
This somehow refs https://github.com/sindresorhus/awesome/issues/784#issuecomment-384223195.

**Comment by at15** [comment]
Already finished the switch and dealing with all the open issues for adding database now. 

Vuepress has built in search and you can do filter based on properties of databases (e.g. status (half of them are dead already ...). 

Will add benchmark, papers and link them with databases later.
